### ISSUE TITLE
Asset path is ignored

### ISSUE THREAD

**Issue by kalouantonis** [aJchemist/boot-figwheel#1]
Hi,

I've been trying to set up boot with figwheel for days now and it seems like the compiler :asset-path values aren't been used. It looks like [this line here](https://github.com/aJchemist/boot-figwheel/blob/master/src/boot_figwheel.clj#L49) might be the culprit. Any ideas?

This is my config: 

```
:compiler {:asset-path "cljs/dev.out"
                 :output-to "cljs/app.js"
                 :optimizations :none
                 :main 'johan-sa.core
                 :pretty-print true}
```

Thanks.

**Comment by ajchemist** [comment]
good catch!

please check https://github.com/aJchemist/boot-figwheel/commit/93a48c1bdaf8a4935b23d8997082f90031bae28d or `0.5.0-1`.

**Comment by kalouantonis** [comment]
Thanks! 

One more thing though, shouldn't `:output-dir` also have the `:target-path` appended to it, like `:output-to` [here](https://github.com/aJchemist/boot-figwheel/blob/master/src/boot_figwheel.clj#L40)?

**Comment by ajchemist** [comment]
- `:output-to` always be prefixed with `:target-path`.
- `:output-dir` would be in same directory where `:output-to` be, unless `:output-dir` is specified.

so in your case,
- `:output-to`    -> `"target/cljs/app.js"`
- `:output-dir`  -> `"target/cljs/dev.out"` (not specified)
- `:asset-path` -> `"cljs/dev.out"` (specified)

**Comment by kalouantonis** [comment]
Right, but in the case that I specify `:output-dir` I'd have to do this:

```
(set-env! :target-path "resources/public")

;; Compiler flags
{:output-to "cljs/app.js"
 :output-dir "resources/public/cljs/out"
 :asset-path "cljs/out"}
```

I'm saying it would make more sense if when I'm specifying `:output-dir` it works like `:output-to` in the sense that it prefixes the given path with `:target-path`. I could be wrong, but I'd expect something like this:

```
(set-env! :target-path "resources/public")

;; Compiler flags
{:output-to "cljs/app.js"
 :output-dir "cljs/out"
 :asset-path "cljs/out"}
```

**Comment by ajchemist** [comment]
why not try this? more short

```
(set-env! :target-path "resources/public")

;; Compiler flags
{:output-to "cljs/app.js"}
```

I have written this sort of directory calculation things for brevity.

**Comment by kalouantonis** [comment]
Yep, works like a charm. Thanks for all your help.
