### ISSUE TITLE
Make boot-figwheel boot friendly again

### ISSUE THREAD

**Issue by arichiardi** [aJchemist/boot-figwheel#4]
I have been thinking about using figwheel again given the tremendous amount of work Bruce is putting in it and the wonderful error reporting the `0.5.4` will have.

Now that Figwheel uses component underneat, is there anything we can do in order to "disable" the custom file watching and kind of have figwheel compatible with the boot pipeline again?

Premise: I have not investigated, just planting the seed here :smile:

**Comment by ajchemist** [comment]
Let me think about this.

currently boot-figwheel intent to mimic api that exists in figwheel-sidecar.repl-api, and use figwheel's own fileset watcher for code reloading. This makes quite easier (for me) to handle figwheel in boot.repl by now, e.g triggering autobuild, hotswap cljs build configurations, and more. 

by the way, boot-figwheel has been dealing with figwheel's component system.

**Comment by arichiardi** [comment]
I'd be happy to help. It there is way to compilation (and sending messages over the websocket) every time the boot handler is called...well we can at that point use it in a watch.
I don't know if this makes sense or is completely out of the world. I will investigate more as well.

**Comment by ajchemist** [comment]
To do so, we should use boot `watch` task AFAIK, but for now, boot `watch` task can't be cooperated with boot-figwheel.

**Comment by arichiardi** [comment]
Maybe then just have an autostart option whenever you execute a task? I am just a bit lazy and would like to avoid  the autobulild start/stop 😃

**Comment by ajchemist** [comment]
@arichiardi hmm, wait a sec. Maybe it is possible when you use with `boot figwheel watch target -C`. call `target` task with :no-clean option.

**Comment by ajchemist** [comment]
At the time that I wrote boot-figwheel, there is no `target` task. but recently boot has changed a lot, so maybe I can revise some stuff for according with boot.

**Comment by arichiardi** [comment]
Oh great! Just brainstorming here, ideally you have an option for autostarting the nrepl (to which you can connect from cider/Cursive) and recompile when the watch task triggers.
But the second step is not that important if figwheel can observe file changes itself...
I would be more keen on the first..

**Comment by arichiardi** [comment]
Idea, what if we could trigger the [build-once](https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/system.clj#L349) every time the task is called?

**Comment by ajchemist** [comment]
By the way, there is another good alternative for now. maybe this is more boot friendly.

``` clojure
(comp
   (serve :dir "target")
   (watch)
   (speak)
   (reload
    :ids #{"app"}
    :on-jsload 'app.core/main)
   (cljs-repl)
   (cljs :ids #{"app"}
         :optimizations :none
         :compiler-options (merge none-opts {:asset-path "/app.out"}))
   (target))
```

**Comment by arichiardi** [comment]
Yes I am using `boot-cljs` but Bruce has got an edge with his very nice compile time error messages...

**Comment by ajchemist** [comment]
@arichiardi if you try to use `build-once`, use `boot-figwheel/build-once` or wrap it in your own task.

**Comment by ajchemist** [comment]
boot-figwheel's `figwheel` task is not cljs building op task. It just do setting build configuration, not building.

**Comment by arichiardi** [comment]
Ok thanks al lot then for the suggestion. Closing this!
