### ISSUE TITLE
Unable to start figwheel repl

### ISSUE THREAD

**Issue by cldwalker** [aJchemist/boot-figwheel#7]
Hi. I'm able to use figwheel's autoload and that is awesome. However, I'm unable to start a figwheel repl using the repl instructions in [usage](https://github.com/aJchemist/boot-figwheel#usage) on the sample projects. For cljs-devtools-sample and rum-mdl, I've respectively spun up a repl server with `boot demo` and `boot dev repl -s wait`. I then spin up a client repl with `boot repl -c -p NUM -H 127.0.0.1`. I'm able to run most of the repl commands but when I run the figwheel repl I get a piggieback failure:

```
boot.user=> (fw-cljs-repl)
Launching ClojureScript REPL for build: dev
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (print-config [id ...])         ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
Failed to launch Figwheel CLJS REPL: nREPL connection found but unable to load piggieback.
Please install https://github.com/cemerick/piggieback

java.lang.Exception: Failed to launch Figwheel CLJS REPL: nREPL connection found but unable to load
piggieback.
                     Please install https://github.com/cemerick/piggieback
```

Do you start the boot client repl in a different way? I didn't see any explicit instructions for starting the boot client repl. Fwiw, I'm on osx 10.11.4
Thanks for the sweet project!

**Comment by cldwalker** [comment]
I'm guessing not [setting up piggieback's middleware](https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl#launching-the-figwheel-cljs-repl) is the culprit. Any steps on how you do this would be helpful

**Comment by cldwalker** [comment]
I was able to resolve this issue by adding the following in build.boot:

```
(require 'boot.repl)
(swap! boot.repl/*default-middleware*
       conj 'cemerick.piggieback/wrap-cljs-repl)
```

May be worth adding some instructions on starting a repl client for those like myself who aren't as familiar with boot

**Comment by ajchemist** [comment]
Oh, I'm a CIDER user so I could not care to use it other toolings.

I'll update the docs.

**Comment by cldwalker** [comment]
Great. Thanks!
