### ISSUE TITLE
Unable to run `boot demo` on cljs-devtools-sample

### ISSUE THREAD

**Issue by groundedsage** [aJchemist/boot-figwheel#8]
When I run `boot demo` on the cljs-devtools-sample project I get this back.

`Require figwheel-sidecar.system just-in-time...
clojure.lang.ExceptionInfo: No such var: string/index-of
    data: {:file "cljs/source_map.clj", :line 260}`

**Comment by ajchemist** [comment]
@CommonCreative I cannot reproduce this issue.

```
$ git clone --recursive https://github.com/aJchemist/boot-figwheel
$ cd boot-figwheel/example/cljs-devtools-sample/
$ boot demo
Require figwheel-sidecar.system just-in-time...
Figwheel: Starting server at http://0.0.0.0:7000
Figwheel: Watching build - demo
Figwheel: Cleaning build - demo
Compiling "resources/public/_compiled/demo/devtools_sample.js" from ["src/demo"]...
WARNING: uuid? already refers to: cljs.core/uuid? being replaced by: cognitect.transit/uuid? at line 342 resources/public/_compiled/demo/cognitect/transit.cljs
Successfully compiled "resources/public/_compiled/demo/devtools_sample.js" in 30.45 seconds.
nREPL server started on port 56923 on host 127.0.0.1 - nrepl://127.0.0.1:56923
```

**Comment by groundedsage** [comment]
@aJchemist thanks for taking a look. I just followed what you have done there. Even after removing Figwheel from the local repository.

Wades-Air:~ wade$ **git clone --recursive https://github.com/aJchemist/boot-figwheel**
Cloning into 'boot-figwheel'...
remote: Counting objects: 286, done.
remote: Total 286 (delta 0), reused 0 (delta 0), pack-reused 286
Receiving objects: 100% (286/286), 52.59 KiB | 67.00 KiB/s, done.
Resolving deltas: 100% (135/135), done.
Submodule 'cljs-devtools-sample' (https://github.com/aJchemist/cljs-devtools-sample) registered for path 'example/cljs-devtools-sample'
Cloning into '/Users/wade/boot-figwheel/example/cljs-devtools-sample'...
Submodule path 'example/cljs-devtools-sample': checked out '91e3d76dd5144990e7fa3e718c09502565791d77'

Wades-Air:~ wade$ **cd boot-figwheel/example/cljs-devtools-sample/**

Wades-Air:cljs-devtools-sample wade$ **boot demo**
Retrieving figwheel-sidecar-0.5.7.pom from https://clojars.org/repo/
Retrieving figwheel-0.5.7.pom from https://clojars.org/repo/
Retrieving figwheel-0.5.7.jar from https://clojars.org/repo/ (21k)
Retrieving figwheel-sidecar-0.5.7.jar from https://clojars.org/repo/ (299k)
Require figwheel-sidecar.system just-in-time...
clojure.lang.ExceptionInfo: **No such var: string/index-of
    data: {:file "cljs/source_map.clj", :line 260}**
java.lang.RuntimeException: No such var: string/index-of

**Comment by ajchemist** [comment]
weird. please check your ~/.boot directory's files
- ~/.boot/profile.boot
- ~/.boot/boot.properties

**Comment by groundedsage** [comment]
**boot.properties** contains
#http://boot-clj.com
#Thu Sep 22 22:31:32 AEST 2016
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.6.0
BOOT_CLOJURE_VERSION=1.7.0

I don't appear to have a **profile.boot**

**Comment by ajchemist** [comment]
@CommonCreative the problem is `BOOT_CLOJURE_VERSION=1.7.0`

`BOOT_CLOJURE_VERSION=1.8.0` would work.

**Comment by groundedsage** [comment]
That eliminates the error thanks! Now back to working out how I can replace reload in the Tenzing template :)
